# Generated by Django 5.1.1 on 2024-09-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("OVERDUE", "Overdue"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
